### PR TITLE
- added isFatal switch on violations, allowing more fine grained beha…

### PR DESCRIPTION
**Pull request by packux**
…viours on calles in case a Failure occures. By default, all violations are considered fatal.

### CODE REVIEW

**Comment by holograph** [comment]
Can you give an example use-case for this? It seems to me _any_ validation failure is fatal by nature.

**Comment by packux** [comment]
The main reason to add an 'isFatal' to the validation is so as to enable cases where we want to raise a Warning, instead of completely failing the validation process.

I guess it would be better/cleaner if an appropriate result type was instead foreseen (i.e. Success/Failure/Warning). Let me know how you think about it and I would be quite keen to do the re-factoring.

**Comment by holograph** [comment]
Can you give an example of what constitutes a warning?

Regardless, here are some things to consider:

* The same validation can result in either warning/fatal. This determination can only be made at the definition site, at the discretion of the engineer designing the validation rule set. This means the DSL will have to support this. Without giving it any careful consideration, my thought is to enable an `orElse warn` modifier suffix; that way the default is fatal, but you can specify rules like `p.firstName is notEmpty orElse warn`.
* Whether or not the validation _result_ is fatal depends on its associated violations, and the result model should probably handle both. I perceive the rule set as follows:
  * `Failure` becomes an abstract base trait for `NonFatal(warnings: Set[Violation])` and `Fatal(violations: Set[Violation], warnings: Set[Violation])`
  * `Success and NonFatal(warnings) == NonFatal(warnings)`
  * `Success and Fatal(violations, warnings) == Fatal(violations, warnings)`
  * `NonFatal(leftWarnings) and NonFatal(rightWarnings) == NonFatal(leftWarnigns ++ rightWarnings)`
  * `NonFatal(leftWarnings) and Fatal(violations, rightWarnings) == Fatal(violations, leftWarnings ++ rightWarnings)`
  * `Fatal(leftViolations, leftWarnings) and Fatal(rightViolations, rightWarnings) == Fatal(leftViolations ++ rightViolations, leftWarnings ++ rightWarnings)`

This is comprehensive but feels over-verbose. I'm still not convinced this is a worthwhile first-class concept, both because I can't conceive of examples (the only practical use cases I can imagine involve UI, and I'd expect such warnings to be mostly in the pre-submit logic), and because I haven't seen another framework support it. Additional discussion may help change my mind :-)

**Comment by holograph** [comment]
No response on this and I still can't see the value, closing for now.

**Pull request closed without merging**
